using System;
using Content.Client.Guidebook.RichText;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Examine;

[GenerateTypedNameReferences]
public sealed partial class ExamineTooltip : Control, ILinkClickHandler
{
    public event Action<string>? OnLinkClicked;

    public ExamineTooltip()
    {
        RobustXamlLoader.Load(this);
    }

    public void HandleClick(string link)
    {
        OnLinkClicked?.Invoke(link);
    }
}
