using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminTab : Control
    {
        public AdminTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            ShiftPanelButton.OnPressed += _ => OpenShiftPanelWindow();
        }

        private void OpenShiftPanelWindow()
        {
            var window = new ShiftSettingsWindow();
            window.OpenCentered();
        }
    }
}
