using Content.Client.Consent;
using Content.Shared.Consent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class ConsentPreferencesTab : BoxContainer
{
    [Dependency] private readonly IClientConsentManager _consentManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    private readonly List<ConsentToggleEntry> _toggleEntries = new();

    public event Action? OnConsentChanged;

    public ConsentPreferencesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CharacterConsentFreetext.Placeholder = new Rope.Leaf(Loc.GetString("consent-prefs-character-freetext-placeholder"));
        CharacterConsentFreetext.OnTextChanged += _ => OnConsentChanged?.Invoke();

        AccountConsentFreetext.Placeholder = new Rope.Leaf(Loc.GetString("consent-prefs-account-freetext-placeholder"));
        AccountConsentFreetext.OnTextChanged += _ => SaveAccountConsent();

        PopulateToggles();
        UpdateAccountConsent();
        LoadConsentToggles();

        _consentManager.OnServerDataLoaded += UpdateAccountConsent;
    }

    /// <summary>
    /// Gets the current character-specific freetext.
    /// </summary>
    public string GetCharacterFreetext()
    {
        return Rope.Collapse(CharacterConsentFreetext.TextRope).Trim();
    }

    /// <summary>
    /// Sets the character-specific freetext.
    /// </summary>
    public void SetCharacterFreetext(string text)
    {
        CharacterConsentFreetext.TextRope = new Rope.Leaf(text);
    }

    /// <summary>
    /// Gets the current account-wide freetext.
    /// </summary>
    public string GetAccountFreetext()
    {
        return Rope.Collapse(AccountConsentFreetext.TextRope).Trim();
    }

    /// <summary>
    /// Sets the account-wide freetext.
    /// </summary>
    public void SetAccountFreetext(string text)
    {
        AccountConsentFreetext.TextRope = new Rope.Leaf(text);
    }

    /// <summary>
    /// Gets the current consent toggle states (only those that are enabled).
    /// </summary>
    public Dictionary<ProtoId<ConsentTogglePrototype>, string> GetToggles()
    {
        var toggles = new Dictionary<ProtoId<ConsentTogglePrototype>, string>();

        foreach (var entry in _toggleEntries)
        {
            if (entry.OnButton.Pressed)
                toggles[entry.Prototype.ID] = "on";
        }

        return toggles;
    }

    /// <summary>
    /// Sets the consent toggle states.
    /// </summary>
    public void SetToggles(Dictionary<ProtoId<ConsentTogglePrototype>, string> toggles)
    {
        foreach (var entry in _toggleEntries)
        {
            var isOn = toggles.TryGetValue(entry.Prototype.ID, out var value) && value == "on";
            entry.OnButton.Pressed = isOn;
            entry.OffButton.Pressed = !isOn;
        }
    }

    /// <summary>
    /// Saves the current toggle states to the consent manager.
    /// </summary>
    private void SaveConsentToggles()
    {
        if (!_consentManager.HasLoaded)
            return;

        var consent = _consentManager.GetConsent();
        var toggles = GetToggles();

        var updatedConsent = new PlayerConsentSettings(
            consent.Freetext,
            consent.CharacterFreetext,
            toggles);

        _consentManager.UpdateConsent(updatedConsent);
    }

    /// <summary>
    /// Saves the account freetext to the consent manager.
    /// </summary>
    private void SaveAccountConsent()
    {
        if (!_consentManager.HasLoaded)
            return;

        var consent = _consentManager.GetConsent();
        var accountFreetext = GetAccountFreetext();
        var toggles = GetToggles();

        var updatedConsent = new PlayerConsentSettings(
            accountFreetext,
            consent.CharacterFreetext,
            toggles);

        _consentManager.UpdateConsent(updatedConsent);
    }

    /// <summary>
    /// Loads the current toggle states from the consent manager.
    /// </summary>
    private void LoadConsentToggles()
    {
        if (!_consentManager.HasLoaded)
            return;

        var consent = _consentManager.GetConsent();
        SetToggles(consent.Toggles);
    }

    private void UpdateAccountConsent()
    {
        if (!_consentManager.HasLoaded)
        {
            AccountConsentFreetext.TextRope = new Rope.Leaf("");
            AccountConsentFreetext.Editable = false;
            return;
        }

        var consent = _consentManager.GetConsent();
        AccountConsentFreetext.TextRope = new Rope.Leaf(consent.Freetext ?? "");
        AccountConsentFreetext.Editable = true;

        // Also reload toggles when account data is updated
        LoadConsentToggles();
    }

    private void PopulateToggles()
    {
        ConsentTogglesGrid.DisposeAllChildren();
        _toggleEntries.Clear();

        var consentPrototypes = _protoManager.EnumeratePrototypes<ConsentTogglePrototype>()
            .Where(p => !p.Unused)
            .OrderBy(p => p)
            .ToList();

        foreach (var prototype in consentPrototypes)
        {
            var container = new PanelContainer
            {
                HorizontalExpand = true
            };
            container.StyleClasses.Add("PdaBorderRect");
            container.Margin = new Thickness(2);

            var innerBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(5),
                HorizontalExpand = true
            };

            // Header with name and toggle buttons
            var header = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };

            var name = new RichTextLabel
            {
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };
            name.SetMessage(FormattedMessage.FromMarkup(Loc.GetString($"consent-{prototype.ID}-name")));

            var buttonOff = new Button
            {
                Text = Loc.GetString("consent-toggle-off"),
                MinWidth = 45
            };
            buttonOff.StyleClasses.Add("OpenRight");
            buttonOff.Pressed = true;

            var buttonOn = new Button
            {
                Text = Loc.GetString("consent-toggle-on"),
                MinWidth = 45
            };
            buttonOn.StyleClasses.Add("OpenLeft");

            buttonOff.OnPressed += _ =>
            {
                buttonOff.Pressed = true;
                buttonOn.Pressed = false;
                OnConsentChanged?.Invoke();
                SaveConsentToggles();
            };

            buttonOn.OnPressed += _ =>
            {
                buttonOn.Pressed = true;
                buttonOff.Pressed = false;
                OnConsentChanged?.Invoke();
                SaveConsentToggles();
            };

            header.AddChild(name);
            header.AddChild(buttonOff);
            header.AddChild(buttonOn);

            // Description with word wrapping
            var desc = new RichTextLabel
            {
                HorizontalExpand = true
            };
            var descMessage = new FormattedMessage();
            descMessage.PushColor(Color.LightGray);
            descMessage.AddText(Loc.GetString($"consent-{prototype.ID}-desc"));
            descMessage.Pop();
            desc.SetMessage(descMessage);

            innerBox.AddChild(header);
            innerBox.AddChild(desc);
            container.AddChild(innerBox);

            ConsentTogglesGrid.AddChild(container);

            _toggleEntries.Add(new ConsentToggleEntry
            {
                Prototype = prototype,
                OnButton = buttonOn,
                OffButton = buttonOff
            });
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            _consentManager.OnServerDataLoaded -= UpdateAccountConsent;
        }
    }

    private struct ConsentToggleEntry
    {
        public ConsentTogglePrototype Prototype;
        public Button OnButton;
        public Button OffButton;
    }
}
