using Content.Client.Lobby.UI.Roles;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitCategoryWindow : DefaultWindow
{
    private readonly IPrototypeManager _prototypeManager;
    private readonly string _categoryId;
    private readonly List<string> _categoryTraits;
    private readonly TraitCategoryPrototype? _category;
    private readonly List<TraitPreferenceSelector> _selectors = new();
    private HumanoidCharacterProfile? _workingProfile;
    private bool _isInitializing = false;
    
    public event Action<HumanoidCharacterProfile?>? OnSave;

    public TraitCategoryWindow(
        IPrototypeManager prototypeManager,
        string categoryId,
        List<string> categoryTraits,
        HumanoidCharacterProfile? currentProfile)
    {
        RobustXamlLoader.Load(this);
        
        _prototypeManager = prototypeManager;
        _categoryId = categoryId;
        _categoryTraits = categoryTraits;
        _workingProfile = currentProfile;
        
        // Get category prototype if not default
        if (categoryId != TraitCategoryPrototype.Default)
        {
            _category = _prototypeManager.Index<TraitCategoryPrototype>(categoryId);
            CategoryTitle.Text = Loc.GetString(_category.Name);
        }
        else
        {
            CategoryTitle.Text = Loc.GetString("trait-window-default-category");
        }
        
        SaveButton.OnPressed += _ => OnSavePressed();
        CancelButton.OnPressed += _ => Close();
        
        PopulateTraits();
        UpdateSelectionCounter();
        UpdateSelectorColors();
    }

    private void PopulateTraits()
    {
        TraitsContainer.DisposeAllChildren();
        _selectors.Clear();
        _isInitializing = true;
        
        foreach (var traitId in _categoryTraits)
        {
            var trait = _prototypeManager.Index<TraitPrototype>(traitId);
            var selector = new TraitPreferenceSelector(trait);
            
            _selectors.Add(selector);
            
            // Set initial preference state
            selector.Preference = _workingProfile?.TraitPreferences.Contains(trait.ID) == true;
            
            // Connect the event handler
            selector.PreferenceChanged += newValue => OnPreferenceChanged(selector, newValue);
            
            TraitsContainer.AddChild(selector);
        }
        
        _isInitializing = false;
    }

    private void OnPreferenceChanged(TraitPreferenceSelector changedSelector, bool newValue)
    {
        // Skip validation during initial population
        if (_isInitializing)
            return;
            
        // If trying to enable and it would exceed max points, prevent it
        if (newValue && _category is { MaxTraitPoints: >= 0 })
        {
            var currentCost = 0;
            foreach (var selector in _selectors)
            {
                if (selector.Preference && selector != changedSelector)
                    currentCost += selector.Cost;
            }
            
            if (currentCost + changedSelector.Cost > _category.MaxTraitPoints)
            {
                // Revert the change - need to suppress event to avoid infinite loop
                changedSelector.Preference = false;
                return;
            }
        }
        
        UpdateSelectionCounter();
        UpdateSelectorColors();
    }

    private void UpdateSelectionCounter()
    {
        if (_category is not { MaxTraitPoints: >= 0 })
        {
            SelectionCounter.Visible = false;
            return;
        }

        SelectionCounter.Visible = true;
        var currentCost = 0;
        
        foreach (var selector in _selectors)
        {
            if (selector.Preference)
                currentCost += selector.Cost;
        }
        
        SelectionCounter.Text = Loc.GetString("humanoid-profile-editor-trait-count-hint", 
            ("current", currentCost), 
            ("max", _category.MaxTraitPoints));
    }

    private void UpdateSelectorColors()
    {
        if (_category is not { MaxTraitPoints: >= 0 })
            return;

        var currentCost = 0;
        foreach (var selector in _selectors)
        {
            if (selector.Preference)
                currentCost += selector.Cost;
        }

        foreach (var selector in _selectors)
        {
            if (!selector.Preference && selector.Cost + currentCost > _category.MaxTraitPoints)
            {
                selector.Checkbox.Label.FontColorOverride = Color.Red;
            }
            else
            {
                selector.Checkbox.Label.FontColorOverride = null;
            }
        }
    }

    private void OnSavePressed()
    {
        // Build the updated profile with selected traits
        var updatedProfile = _workingProfile;
        
        foreach (var selector in _selectors)
        {
            var trait = _prototypeManager.Index<TraitPrototype>(_categoryTraits[_selectors.IndexOf(selector)]);
            
            if (selector.Preference && updatedProfile?.TraitPreferences.Contains(trait.ID) != true)
            {
                updatedProfile = updatedProfile?.WithTraitPreference(trait.ID, _prototypeManager);
            }
            else if (!selector.Preference && updatedProfile?.TraitPreferences.Contains(trait.ID) == true)
            {
                updatedProfile = updatedProfile?.WithoutTraitPreference(trait.ID, _prototypeManager);
            }
        }
        
        OnSave?.Invoke(updatedProfile);
        Close();
    }
}
