using System.Linq;
using System.Numerics;
using Content.Shared.Tools;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Tools;

[GenerateTypedNameReferences]
public sealed partial class TransformationToolWindow : DefaultWindow
{
    public event Action? OnClearScan;
    public event Action<NetEntity>? OnRevert;
    public event Action? OnRevertAll;
    public event Action<float>? OnSetDuration;

    public TransformationToolWindow()
    {
        RobustXamlLoader.Load(this);

        ClearScanButton.OnPressed += _ => OnClearScan?.Invoke();
        RevertAllButton.OnPressed += _ => OnRevertAll?.Invoke();
        DurationInput.OnTextEntered += args =>
        {
            if (float.TryParse(args.Text, out var duration))
            {
                OnSetDuration?.Invoke(duration);
            }
        };
    }

    public void UpdateState(TransformationToolBoundUserInterfaceState state)
    {
        // Update scanned entity label
        ScannedLabel.Text = state.ScannedName ?? "None";
        ClearScanButton.Disabled = state.ScannedName == null;

        // Update duration input (in minutes)
        DurationInput.Text = state.DefaultDurationMinutes.ToString();

        // Update transformations list
        TransformationsList.RemoveAllChildren();

        if (state.ActiveTransformations.Count == 0)
        {
            var label = new Label { Text = "No active transformations", StyleClasses = { "LabelSubText" } };
            TransformationsList.AddChild(label);
        }
        else
        {
            foreach (var (transformed, original) in state.ActiveTransformations)
            {
                var container = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new Thickness(0, 2)
                };

                var label = new Label
                {
                    Text = $"Entity {transformed}",
                    HorizontalExpand = true
                };

                var revertButton = new Button
                {
                    Text = "Revert",
                    MinSize = new Vector2(60, 0)
                };
                revertButton.OnPressed += _ => OnRevert?.Invoke(transformed);

                container.AddChild(label);
                container.AddChild(revertButton);
                TransformationsList.AddChild(container);
            }
        }

        RevertAllButton.Disabled = state.ActiveTransformations.Count == 0;
    }
}
